language: python
python:
    - 3.4
    - 3.3
    - 2.7
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    # temporary while renaming propagates
    - pip install --no-deps -e git+https://github.com/jupyter/jupyter_notebook#egg=jupyter_notebook
    - pip install -f travis-wheels/wheelhouse . coveralls -r requirements.txt
    - pip install nbconvert[execute,serve,test]
    - python -c 'import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)'
script:
    - nosetests --with-coverage --cover-package nbconvert nbconvert
after_success:
    - coveralls
