language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/bin:$PATH
sudo: false
addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-xetex
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - wget http://c90cb902a90d6a506ab3-a24171cbeaa42ce11788f0df3362e902.r46.cf5.rackcdn.com/pandoc-1.15.0.6.tar.gz && tar -xzf pandoc-1.15.0.6.tar.gz
    - pip install -f travis-wheels/wheelhouse . codecov coverage
    - pip install nbconvert[execute,serve,test]
    - python -m ipykernel.kernelspec --user
script:
    # cd so we test the install, not the repo
    - cd `mktemp -d`
    - py.test --cov nbconvert -v --pyargs nbconvert
after_success:
    - codecov
